"""Pack Blender output into direct flash-backed LVGL RGB565 frames, no decoder RAM."""
from pathlib import Path
import hashlib,json,struct
from PIL import Image
ROOT=Path(__file__).resolve().parents[2]
ui=ROOT/'firmware/wheel/components/wheel_ui';src=ROOT/'.test-build/e90-render'
frames=[f'boot_{i:02d}' for i in range(28)]+[f'closure_{i:02d}' for i in range(64)]
data=bytearray();previews=ROOT/'docs/design/e90-closure-camera/renders'
previews.mkdir(parents=True,exist_ok=True)
for name in frames:
 im=Image.open(src/(name+'.png')).convert('RGBA')
 bg=Image.new('RGBA',im.size,(9,13,28,255));bg.alpha_composite(im)
 rgb=bg.convert('RGB').resize((192,104),Image.Resampling.LANCZOS)
 for r,g,b in rgb.get_flattened_data():data+=struct.pack('<H',((r>>3)<<11)|((g>>2)<<5)|(b>>3))
 if name in ['closure_00','closure_01','closure_02','closure_03','closure_04','closure_08','closure_16','closure_32','closure_63','boot_00','boot_03','boot_05','boot_14','boot_23','boot_24','boot_25','boot_26','boot_27']:
  rgb.save(previews/(name+'.png'))
assert len(data)==92*192*104*2
(ui/'ui_vehicle_frames.bin').write_bytes(data)
lines=['/* Generated by tools/assets/pack_e90.py; see assets/ui/e90/ATTRIBUTION.md. */','#include "ui_vehicle_assets.h"','extern const uint8_t _binary_ui_vehicle_frames_bin_start[];','static const lv_image_dsc_t frames[92] = {']
for i in range(92):
 lines.append('{.header={.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_RGB565,.flags=0,.w=192,.h=104,.stride=384},.data_size=39936,.data=_binary_ui_vehicle_frames_bin_start+%du},'%(i*39936))
lines+=['};','const lv_image_dsc_t *ui_vehicle_asset(bool boot,unsigned frame) {','  if (frame >= (boot ? 28u : 64u)) return NULL;','  return &frames[(boot ? 0u : 28u)+frame];','}']
(ui/'ui_vehicle_assets.c').write_text('\n'.join(lines)+'\n',encoding='utf-8')
manifest={'format':'RGB565 little-endian','width':192,'height':104,'boot_frames':28,'closure_frames':64,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest(),'source_zip_sha256':'fa702396d7fa54054831ff67823b010e90521b221e2625b4222888b36edd6eb9','frames':frames}
(previews.parent/'asset-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Packed',len(data),'bytes;',manifest['sha256'])
